### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by haozewu** [Li-Siyuan/KEA128-Project#1]
# delete
删除NRF的引脚
删除驱动输入的下拉电阻
删除隔离芯片不用的引脚
因为总供电电压是3V3，省略一些按键的10k电阻
# add
需要为Zigbee引出一个USART来直插

**Comment by zhaokun0** [comment]
晶振并联一个100k的电阻，且晶振靠近芯片放置。
6个滤波电容靠近芯片放置。
去掉多余的电源灯。
在丝印上标好模块名，编码器标出凸起朝向。
加上保险丝。

**Comment by haozewu** [comment]
咱们UART只为zigbee提供吗？如果是的话就直接改管脚换排母了
